### ISSUE TITLE
Docker build fails

### ISSUE THREAD

**Issue by Fab7c4** [jwkvam/bowtie#170]
Executing `docker build . -t bowtie` terminates with the following error

```
Fetching list of valid trove classifiers                I-flit.inifile
Traceback (most recent call last):
  File "/opt/conda/bin/flit", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.6/site-packages/flit/__init__.py", line 143, in main
    symlink=args.symlink, deps=args.deps, pth=args.pth_file).install()
  File "/opt/conda/lib/python3.6/site-packages/flit/install.py", line 104, in __init__
    raise RootInstallError
flit.install.RootInstallError: Installing packages as root is not recommended. To allow this, set FLIT_ROOT_INSTALL=1 and try again.
The command '/bin/sh -c flit install' returned a non-zero code: 1
```

**Comment by jwkvam** [comment]
Thanks for reporting, I just fixed this in master. In general though the docker workflow needs some attention.

I'll close this since the docker builds for me now, but please reopen if it doesn't work for you.
